export default {
  NONE: {
    ad: false,
    exchange: false,
    video: false,
    widget: false,
    gtag: false,
    amp: false,
  },
  LITE: {
    ad: true,
    exchange: true,
    video: true,
    widget: true,
    gtag: true,
    amp: true,
  },
  ADEX: {
    ad: true,
    exchange: true,
    video: false,
    widget: false,
    gtag: false,
    amp: false,
  },
  AD: {
    ad: true,
    exchange: false,
    video: false,
    widget: false,
    gtag: false,
    amp: false,
  },
  EX: {
    ad: false,
    exchange: true,
    video: false,
    widget: false,
    gtag: false,
    amp: false,
  },
  CUSTOM: {
    ad: false,
    exchange: false,
    video: false,
    widget: false,
    gtag: false,
    amp: false,
  },
};
